/*
 * ArchiveTune (2026)
 * © Rukamori — github.com/rukamori
 * GPL-3.0 License | Contributors: see git history
 * Do not remove or alter this notice. - Per GPL-3.0 Section 4 & Section 5
 */

package moe.rukamori.archivetune.innertube.models.response

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import moe.rukamori.archivetune.innertube.models.ResponseContext
import moe.rukamori.archivetune.innertube.models.Thumbnails

/**
 * PlayerResponse with [moe.rukamori.archivetune.innertube.models.YouTubeClient.WEB_REMIX] client
 */
@Serializable
data class PlayerResponse(
    val responseContext: ResponseContext,
    val playabilityStatus: PlayabilityStatus,
    val playerConfig: PlayerConfig?,
    val streamingData: StreamingData?,
    val videoDetails: VideoDetails?,
    val captions: Captions? = null,
    @SerialName("playbackTracking")
    val playbackTracking: PlaybackTracking?,
) {
    /**
     * Caption track list returned by YouTube's /player endpoint.
     *
     * Each [CaptionTrack] has a `baseUrl` that points to a timedtext endpoint.
     * The default response format is XML (TTML-ish); appending `&fmt=vtt` to
     * the baseUrl makes YouTube return WebVTT, which ExoPlayer parses
     * natively without a custom decoder.
     */
    @Serializable
    data class Captions(
        @SerialName("playerCaptionsTracklistRenderer")
        val playerCaptionsTracklistRenderer: PlayerCaptionsTracklistRenderer?,
    ) {
        @Serializable
        data class PlayerCaptionsTracklistRenderer(
            @SerialName("captionTracks")
            val captionTracks: List<CaptionTrack>? = null,
            @SerialName("defaultAudioTrackIndex")
            val defaultAudioTrackIndex: Int? = null,
        )
    }

    @Serializable
    data class CaptionTrack(
        @SerialName("baseUrl")
        val baseUrl: String,
        @SerialName("name")
        val name: Name?,
        @SerialName("vssId")
        val vssId: String?,
        @SerialName("languageCode")
        val languageCode: String?,
        @SerialName("kind")
        val kind: String?,
        @SerialName("isTranslatable")
        val isTranslatable: Boolean? = null,
    ) {
        @Serializable
        data class Name(
            @SerialName("simpleText")
            val simpleText: String?,
            @SerialName("runs")
            val runs: List<Run>? = null,
        ) {
            @Serializable
            data class Run(val text: String?)

            val displayName: String?
                get() = simpleText ?: runs?.joinToString("") { it.text.orEmpty() }?.takeIf { it.isNotBlank() }
        }

        /** ASR tracks are auto-generated; treat them as lower priority than human-authored. */
        val isAutoGenerated: Boolean get() = kind == "asr"

        /**
         * Returns a WebVTT-format URL for this caption track. YouTube's
         * default baseUrl returns XML; `&fmt=vtt` makes it return WebVTT,
         * which ExoPlayer parses natively.
         */
        fun webVttUrl(): String {
            val separator = if (baseUrl.contains("?")) "&" else "?"
            return if (baseUrl.contains("fmt=")) baseUrl else "$baseUrl${separator}fmt=vtt"
        }
    }

    @Serializable
    data class PlayabilityStatus(
        val status: String,
        val reason: String?,
    )

    @Serializable
    data class PlayerConfig(
        val audioConfig: AudioConfig,
    ) {
        @Serializable
        data class AudioConfig(
            val loudnessDb: Double?,
            val perceptualLoudnessDb: Double?,
        )
    }

    @Serializable
    data class StreamingData(
        val formats: List<Format>?,
        val adaptiveFormats: List<Format>,
        val expiresInSeconds: Int,
    ) {
        @Serializable
        data class Format(
            val itag: Int,
            val url: String?,
            val mimeType: String,
            val bitrate: Int,
            val width: Int?,
            val height: Int?,
            val contentLength: Long?,
            val quality: String,
            val fps: Int?,
            val qualityLabel: String?,
            val averageBitrate: Int?,
            val audioQuality: String?,
            val approxDurationMs: String?,
            val audioSampleRate: Int?,
            val audioChannels: Int?,
            val loudnessDb: Double?,
            val lastModified: Long?,
            val signatureCipher: String?,
            val cipher: String?,
            val audioTrack: AudioTrack?,
        ) {
            val isAudio: Boolean
                get() = width == null
            val isOriginal: Boolean
                get() = audioTrack?.isAutoDubbed == null

            @Serializable
            data class AudioTrack(
                val displayName: String?,
                val id: String?,
                val isAutoDubbed: Boolean?,
            )
        }
    }

    @Serializable
    data class VideoDetails(
        val videoId: String,
        val title: String?,
        val author: String?,
        val channelId: String,
        val lengthSeconds: String,
        val musicVideoType: String?,
        val viewCount: String?,
        val thumbnail: Thumbnails,
    )

    @Serializable
    data class PlaybackTracking(
        @SerialName("videostatsPlaybackUrl")
        val videostatsPlaybackUrl: VideostatsPlaybackUrl?,
        @SerialName("videostatsWatchtimeUrl")
        val videostatsWatchtimeUrl: VideostatsWatchtimeUrl?,
        @SerialName("atrUrl")
        val atrUrl: AtrUrl?,
    ) {
        @Serializable
        data class VideostatsPlaybackUrl(
            @SerialName("baseUrl")
            val baseUrl: String?,
        )

        @Serializable
        data class VideostatsWatchtimeUrl(
            @SerialName("baseUrl")
            val baseUrl: String?,
        )

        @Serializable
        data class AtrUrl(
            @SerialName("baseUrl")
            val baseUrl: String?,
        )
    }
}
